<template>
  <div class="home">

    <div class="home-content">
      <router-view name="a"></router-view>

      <div class="container">

       <div class="columns">

           <router-view name="b" class="column" ></router-view>
           <router-view name="c" class="column" v-if="leftFinished"  ></router-view>

       </div>

      </div>

      <transition appear name="fade">
        <router-view name="d" class=""></router-view>
      </transition>


    </div>

    <transition appear name="fade">
      <div class="particles is-hidden-mobile">
        <router-view name="background"></router-view>
      </div>
    </transition>


  </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: 'home',
  data() {
    return { leftFinished: false };
  },
  components: {
  },

  computed: {
  },
};
</script>
<style>

  .particles {
    position: relative;
    z-index: -100;
  }

  .home-content {
    position:absolute;
    left: 0;
    right: 0;
    margin: auto;
    z-index: 200;
  }
  .home{
    position:relative;
  }

  .fade-enter-active {
    -webkit-animation: fade 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: fade 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  }

  .fade-leave-active {
    -webkit-animation: fade 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) reverse;
    animation: fade 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) reverse;
  }
  /* ----------------------------------------------
   * Generated by Animista on 2018-12-16 4:32:57
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation slide-in-elliptic-top-fwd
   * ----------------------------------------
   */
  /* ----------------------------------------------
   * Generated by Animista on 2018-12-16 4:33:46
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation fade-in
   * ----------------------------------------
   */
  @-webkit-keyframes fade {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }


</style>
