<template>
  <div class="home">

    <div class="home-content">
      <router-view name="a"></router-view>
      <router-view name="b" ></router-view>
      <router-view name="c" class="fade-in"></router-view>
    </div>


    <div class="particles fade-in is-hidden-mobile">
      <router-view name="background"></router-view>
    </div>


  </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: 'home',
  components: {
  },

  computed: {
  },
};
</script>
<style>
  .particles {
    position: relative;
    z-index: -100;
  }
  .home-content {
    position:absolute;
    left: 0;
    right: 0;
    margin: auto;
    z-index: 200;
  }
  .home{
    position:relative;
  }
  .fade-in {
    -webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  }
  /* ----------------------------------------------
   * Generated by Animista on 2018-12-16 4:32:57
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation slide-in-elliptic-top-fwd
   * ----------------------------------------
   */
  /* ----------------------------------------------
   * Generated by Animista on 2018-12-16 4:33:46
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation fade-in
   * ----------------------------------------
   */
  @-webkit-keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }


</style>
