<template>
  <div class="root"
       @click="goToUrl"
       @mouseover="toggleActive"
        @mouseout="toggleActive"
         :class="getActiveClass"
  >

    <svg class="inner-rect" >

      <text id="cb-text" x="50%" y="50%" > {{link.website}} </text>
    </svg>
  </div >

</template>

<script>
export default {
  name: 'ContentBoxSlim',
  props: {
    link: Object,
    index: Number,
  },
  data() {
    return {
      isActive: false,
      colors: ['yellow', 'red', 'green', 'blue'],
    };
  },
  computed: {
    getActiveClass() {
      const activeClass = `activebox${this.colors[this.index].charAt(0).toUpperCase()}`;
      return {
        [activeClass]: this.isActive,
        vibrate1: this.isActive,
        inactivebox: !this.isActive,
      };
    },
  },
  methods: {
    toggleActive() {
      this.isActive = !this.isActive;
    },
    goToUrl() {
      if (this.link.url.substring(0, 4) === 'http') {
        window.location = this.link.url;
      } else {
        this.$router.push(this.link.url);
      }
    },
  },
};
</script>

<style scoped>
  #cb-text{
    fill: #f6f6f6;
    text-anchor: middle;
    font-weight: 600;
  }

  .inner-rect {
    position:relative;
    fill: #393d3f;
    width: 94%;
    height: 88%;
    border-radius: 25px;
    z-index: 1;
  }

  .root {
    z-index: -100;
    positon: absolute;
    overflow: hidden;
    width: 16rem;
    height: 3rem;
    background-color: #444054;

    box-shadow: 0 10px 6px -6px #777;
    border-radius: 5px;
  }

  /* Button focus events */
  .inactivebox {
    background-image: url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 52 26' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%239C92AC' fill-opacity='0.4'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  }
  .activeboxY
  {
    background-image: url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 40 35' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='yellow' fill-opacity='0.4'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  }
  .activeboxR {
    background-image: url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 40 35' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='green' fill-opacity='0.4'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  }
  .activeboxG {
    background-image: url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 40 35' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='pink' fill-opacity='0.4'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  }
  .activeboxB {
    background-image: url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 40 35' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='blue' fill-opacity='0.4'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  }

  /* Animation */
  .vibrate1 {
    -moz-animation: vibrate-1 0.5s 3s cubic-bezier(0.550, 0.055, 0.675, 0.190) infinite both;
    -webkit-animation: vibrate-1 0.5s 3s cubic-bezier(0.550, 0.055, 0.675, 0.190) infinite both;
    animation: vibrate-1 0.4s 3s cubic-bezier(0.550, 0.055, 0.675, 0.190) infinite both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2018-12-15 6:32:56
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation vibrate-1
   * ----------------------------------------
   */
  @-webkit-keyframes vibrate-1 {
    0% {
      -webkit-transform: translate(0);
      transform: translate(0);
    }
    20% {
      -webkit-transform: translate(-2px, 2px);
      transform: translate(-2px, 2px);
    }
    40% {
      -webkit-transform: translate(-2px, -2px);
      transform: translate(-2px, -2px);
    }
    60% {
      -webkit-transform: translate(2px, 2px);
      transform: translate(2px, 2px);
    }
    80% {
      -webkit-transform: translate(2px, -2px);
      transform: translate(2px, -2px);
    }
    100% {
      -webkit-transform: translate(0);
      transform: translate(0);
    }
  }

  @-webkit-keyframes vibrate-1-prelude {
    0% {
      -webkit-transform: skewX(0);
      transform: skewX(0);
    }
    20% {
      -webkit-transform: skewX(20deg);
      transform: skewX(20deg);
    }
    40% {
      -webkit-transform: skewX(20deg);
      transform: skewX(20deg);
    }
    60% {
      -webkit-transform: translate(2px, 2px);
      transform: translate(2px, 2px);
    }
    80% {
      -webkit-transform: translate(2px, -2px);
      transform: translate(2px, -2px);
    }
    100% {
      -webkit-transform: translate(0);
      transform: translate(0);
    }
  }

</style>
