<template>
  <section class="hero is-primary is-medium interactive-header">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
      <div class="navbar-brand">

        <a id="back-button" @click="$router.go(-1)">
              <span class="icon is-medium has-text-info">
                <i class="fas fa-arrow-left"></i>
              </span>
        </a>
      </div>
    </div>

    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
      <div class="container has-text-centered">
        <transition appear name="flip-horizontal">
        <h1 class="title who-header">
            <vue-typer text='$whoami'
                       initial-action='typing' :repeat="0"
                       :pre-type-delay="1200" caret-animation='solid'
                       class="typer"
            ></vue-typer>
        </h1>
        </transition>
      </div>
    </div>

    <!-- Hero footer: will stick at the bottom -->
    <div class="hero-foot">
      <p> footer </p>
    </div>

  </section>

</template>

<script>
export default {
  name: 'InteractiveHeader',
  props: {},
  data() {
    return {};
  },
  computed: {},
  methods: {},
};
</script>

<style scoped>
  .interactive-header {
    background: #393d3f;
    min-height: 100vh;
  }

  .fa-arrow-left {
    color:white;
  }

  #back-button {
    padding: .5rem 0rem 0rem .5rem;
    tranform-origin: 50% 50%;
    transform: scale(1);
    filter: opacity(.7);
    transition: transform 240ms, filter 240ms;
  }

  #back-button:hover {
    filter: opacity(1);
    transform: scale(1.1);
  }

  .vue-typer >>> .custom.char.typed {
    color: ghostwhite;
    font-family: Josefin sans;
  }

  .vue-typer >>> .custom.caret {
    width: 4px;
    background-color: ghostwhite;
  }

  .who-header{
    transform: scale(3);
  }

  .correct-scale {
    -webkit-animation: correct-scale 4s cubic-bezier(0.455, 0.030, 0.515, 0.955) forwards 1;
    animation: correct-scale  4s cubic-bezier(0.455, 0.030, 0.515, 0.955) forwards 1;
  }


  @keyframes correct-scale {
    0% {
      -webkit-transform: scale(3) translateY(0rem);
      transform: scale(3) translateY(0rem);
    }
    30%{
      -webkit-transform: scale(3.1) translateY(-2rem);
      transform: scale(3.1) translateY(-2rem);
    }
    100% {
      -webkit-transform: scale(1) translateY(-4rem);
      transform: scale(1) translateY(-4rem);
    }
  }

  .flip-horizontal-enter-active {
    -webkit-animation: flip-horizontal-bottom 1s
    cubic-bezier(0.455, 0.955, 0.455, 0.955) backwards;

    animation: flip-horizontal-bottom 1s
    cubic-bezier(0.455, 0.955, 0.455, 0.955) backwards ;
  }

  .flip-horizontal-leave-active {
    -webkit-animation: flip-horizontal-bottom 1s
    cubic-bezier(0.455, 0.955, 0.455, 0.955) backwards ;

    animation: flip-horizontal-bottom 1s
    cubic-bezier(0.455, 0.955, 0.455, 0.955) backwards ;
  }

  /* ----------------------------------------------
   * Generated by Animista on 2018-12-28 16:58:19
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation flip-horizontal-bottom
   * ----------------------------------------
   */
  @-webkit-keyframes flip-horizontal-bottom {
    0% {
      -webkit-transform: rotateX(0);
      transform: rotateX(0);
    }
    50% {
      -webkit-transform: rotateX(-180deg);
      transform: rotateX(-180deg);
    }
    75% {
      -webkit-transform: rotateX(-275deg);
      transform: rotateX(-275deg);
    }
    90% {
      -webkit-transform: rotateX(-360deg);
      transform: rotateX(-360deg);
    }
    100% {
      -webkit-transform: rotateX(-360deg);
      transform: rotateX(-360deg);
    }
  }
  @keyframes flip-horizontal-bottom {
    0% {
      -webkit-transform: rotateX(0);
      transform: rotateX(0);
    }
    50% {
      -webkit-transform: rotateX(-180deg);
      transform: rotateX(-180deg);
    }
    75% {
      -webkit-transform: rotateX(-275deg);
      transform: rotateX(-275deg);
    }
    90% {
      -webkit-transform: rotateX(-360deg);
      transform: rotateX(-360deg);
    }
    100% {
      -webkit-transform: rotateX(-360deg);
      transform: rotateX(-360deg);
    }
  }


</style>
