<template>

      <a class="icon is-large icon-link" :href="link.url">
             <i :class="icon"></i>
      </a>


</template>

<script>
export default {
  name: 'MediaButtons',
  props: {
    link: Object,
    icon: String,
  },
  data() {
    return { };
  },
  computed: {
  },
  methods: {
  },
};
</script>
<style scoped>
  .icon-link {
    outline:none;
    transform: scale(1.2);
    color: #444054;
  }
  .icon-link:hover{
    transform: scale(2);
    -webkit-animation: jello-horizontal 0.9s both;
    animation: jello-horizontal 0.9s both;
   }

  /* ----------------------------------------------
   * Generated by Animista on 2018-12-21 3:19:20
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation jello-horizontal
   * ----------------------------------------
   */
  @-webkit-keyframes jello-horizontal {
    0% {
      -webkit-transform: scale(2) scale3d(1, 1, 1);
      transform: scale(2) scale3d(1, 1, 1);
    }
    30% {
      -webkit-transform: scale(2) scale3d(1.25, 0.75, 1);
      transform: scale(2) scale3d(1.25, 0.75, 1);
    }
    40% {
      -webkit-transform: scale3d(0.75, 1.25, 1);
      transform: scale(2) scale3d(0.75, 1.25, 1);
    }
    50% {
      -webkit-transform: scale(2) scale3d(1.15, 0.85, 1);
      transform: scale(2) scale3d(1.15, 0.85, 1);
    }
    65% {
      -webkit-transform: scale(2) scale3d(0.95, 1.05, 1);
      transform: scale(2) scale3d(0.95, 1.05, 1);
    }
    75% {
      -webkit-transform: scale(2) scale3d(1.05, 0.95, 1);
      transform: scale(2) scale3d(1.05, 0.95, 1);
    }
    100% {
      -webkit-transform:scale(2) scale3d(1, 1, 1);
      transform:scale(2) scale3d(1, 1, 1);
    }
  }
  @keyframes jello-horizontal {
    0% {
      -webkit-transform:scale(2) scale3d(1, 1, 1);
      transform:scale(2) scale3d(1, 1, 1);
    }
    30% {
      -webkit-transform:scale(2) scale3d(1.25, 0.75, 1);
      transform: scale(2) scale3d(1.25, 0.75, 1);
    }
    40% {
      -webkit-transform: scale(2) scale3d(0.75, 1.25, 1);
      transform: scale(2) scale3d(0.75, 1.25, 1);
    }
    50% {
      -webkit-transform:scale(2) scale3d(1.15, 0.85, 1);
      transform: scale(2) scale3d(1.15, 0.85, 1);
    }
    65% {
      -webkit-transform:scale(2) scale3d(0.95, 1.05, 1);
      transform:scale(2) scale3d(0.95, 1.05, 1);
    }
    75% {
      -webkit-transform:scale(2) scale3d(1.05, 0.95, 1);
      transform:scale(2) scale3d(1.05, 0.95, 1);
    }
    100% {
      -webkit-transform:scale(2) scale3d(1, 1, 1);
      transform: scale(2) scale3d(1, 1, 1);
    }
  }

</style>
